#!/bin/sh
psql -U $POSTGRES_USER $POSTGRES_DB<<- EOF
    CREATE USER $POSTGRES_INITDB_USERNAME WITH PASSWORD '$POSTGRES_INITDB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE consolidated_server TO $POSTGRES_INITDB_USERNAME;
    CREATE SCHEMA hapi_fhir;
    CREATE SCHEMA keycloak;
    CREATE SCHEMA server_management;
EOF